#! /bin/bash

g++ *.h *.cpp ./Server/*.cpp ./Server/*.h ./Commands/*.cpp ./Commands/*.h -L/usr/lib/arm-linux-gnueabihf -L/usr/lib/ -L/usr/local/lib -lcurl -lboost_system -lpthread -lbcm2835 -I/usr/local/include -I/usr/include/curl -IServer -ICommand -o rasppi_solar -g -Wall -O3
